Created Connection Page
blahajjessie/kakaw pull request #12
Opened 2023-04-23 21:54 UTC by Shea-Scarlet

Added temporary api.ts for testing

2023-04-23 21:55 UTC, Shea-Scarlet commented
Websockets are online!

2023-04-25 17:45 UTC, 190n requested changes
Good work but a couple things need fixing. Read over my changes and then also please format all the code before merging.

2023-04-25 17:45 UTC, 190n commented on backend/.babelrc
Why's this here? I don't think we use Babel on the backend.

2023-04-25 17:45 UTC, 190n commented on frontend/package.json
> +    "test": "jest --coverage"
```suggestion
    "test": "jest --coverage",
```

npm doesn't parse this without the comma

2023-04-25 17:45 UTC, 190n commented on frontend/package.json
> +    "jest-environment-jsdom": "^29.5.0"
```suggestion
    "jest-environment-jsdom": "^29.5.0",
```

2023-04-25 17:45 UTC, 190n commented on frontend/pages/[gameId]/[playerId].tsx
> +import { WEBSOCKET_BASE_URL } from '/Users/gealoro/kakaw/frontend/lib/api';
```suggestion
import { WEBSOCKET_BASE_URL } from '@/lib/api';
```

The current import only works for you. `@` refers to the root of the package (in this case `frontend`).

2023-04-25 17:45 UTC, 190n commented on frontend/pages/[gameId]/[playerId].tsx
> +  }
```suggestion
```

Dead code

2023-04-25 17:45 UTC, 190n commented on frontend/pages/[gameId]/[playerId].tsx
> +
```suggestion
```

2023-04-25 17:45 UTC, 190n commented on frontend/pages/[gameId]/[playerId].tsx
> +  useWebSocket(WS_URL, {
```suggestion
	const router = useRouter();
	const { gameId, playerId } = router.query as {
		gameId: string;
		playerId: string;
	};

	const url = new URL('/connect', WEBSOCKET_BASE_URL);
	url.searchParams.set('gameId', gameId);
	url.searchParams.set('playerId', playerId);

	useWebSocket(url.href, {
```
`WEBSOCKET_BASE_URL` is just the hostname/port we should connect to. So right now it's `ws://localhost:8080` but maybe later we would change it to `wss://kakaw.com` or wherever we might end up hosting this app. You still need to specify `/connect` as well as the query parameters for the game and player IDs.

2023-04-25 17:45 UTC, 190n commented on frontend/pages/[gameId]/[playerId].tsx
> +
```suggestion
```

I moved these up above the `useWebSocket` call.

2023-04-25 17:50 UTC, 190n commented
Also please give your branches descriptive names.

2023-04-27 21:19 UTC, 190n approved these changes

2023-04-27 21:19 UTC, merged