Fix start and end question to send accurate data
blahajjessie/kakaw pull request #38
Opened 2023-05-26 19:36 UTC by blahajjessie

2023-05-26 20:04 UTC, 190n requested changes
`time` is not fixed on `startQuestion` messages.

2023-05-26 20:04 UTC, 190n commented on api-docs/interface/server-socket.md
> +- `responseTime` : number: the ammount of time the player took to answer the question
Should also be fixed in #34 but this should specify milliseconds

2023-05-26 20:04 UTC, 190n commented on api-docs/interface/server-socket.md
> +- `username` (string): the name of the player
apply the fix from #34

2023-05-26 20:06 UTC, 190n commented
`correctAnswers` is not sent on `endQuestion` messages to host.

2023-05-27 23:07 UTC, 190n requested changes

2023-05-27 23:07 UTC, 190n commented on api-docs/interface/player-http.md
> +body: `{name: string}`
username

2023-05-27 23:07 UTC, 190n commented on api-docs/interface/server-socket.md
> +- `explanations` (string[]) : The explanations for right ans wrong answers. TODO (Currently sends an empty array)
String array or null if there aren't explanations

2023-05-27 23:11 UTC, 190n submitted a review, later dismissed

2023-05-28 21:35 UTC, 190n approved these changes, later dismissed

2023-05-28 22:58 UTC, rlchoy submitted a review, later dismissed

2023-05-28 23:02 UTC, celdond requested changes
Typos, there are also failing tests.  Not sure what branch the failures are from however.

2023-05-28 23:02 UTC, celdond commented on api-docs/interface/host-http.md
> +Upon recept of this, the host should display a screen showing a list of players.
Typo, what is 'recept' ?

2023-05-28 23:02 UTC, celdond commented on api-docs/interface/player-http.md
> +Allows a player ot join a game
Typo
```suggestion
Allows a player to join a game
```

2023-05-28 23:03 UTC, 190n commented on api-docs/interface/host-http.md
> +Upon recept of this, the host should display a screen showing a list of players.
probably "receipt". @blahajjessie

2023-05-28 23:09 UTC, celdond approved these changes

2023-05-28 23:10 UTC, 190n approved these changes

2023-05-28 23:22 UTC, merged